apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studio
  namespace: homerun
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - homerun.love
      secretName: homerun-love-tls
  rules:
    - host: homerun.love
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: studio
                port:
                  number: 8080
