apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: studio-data
  namespace: homerun
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: studio-sites
  namespace: homerun
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
